version: "3.8"

services:
  # Symfony API (PHP-FPM)
  api:
    image: my_api_project:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase?serverVersion=16&charset=utf8"
    networks:
      - mynet

  # Database: Postgres
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    networks:
      - mynet

  # Vue frontend
  vue:
    image: my_vue_project:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5173:80"
    networks:
      - mynet

  # Nginx reverse proxy (optional, to unify API + frontend under port 80)
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
      - vue
    networks:
      - mynet

networks:
  mynet:
    driver: overlay

volumes:
  db_data:
