version: "3.9"
#Docker Engine 20.10 and Docker Compose 1.27.1.

services:
  # Database: Postgres
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # ports:
      # - "5432:5432"
    networks: [mynet]

  # Symfony API (PHP-FPM)
  api:
    image: my_project_api:${MY_PROJECT_VERSION}
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase?serverVersion=16&charset=utf8"
    command: >
      sh -c "php bin/console doctrine:migrations:migrate --no-interaction &&
             php-fpm"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # ports:
      # - "9000:9000"
    working_dir: /var/www/html
    # volumes:
      # - ./api:/var/www/html
    networks: [mynet]

  # Vue frontend
  vue:
    # build: ./vue  
    image: my_project_vue:${MY_PROJECT_VERSION}
    environment:
      VITE_BASE_API_URL: "/api"
    # volumes:
    # - ./api/public:/usr/share/nginx/html/public

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
    ports:
      - "80:80"
    networks: [mynet]

networks:
  mynet:
    driver: overlay

volumes:
  db_data:
