version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: no-agent
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        
volumes:
  portainer_data:
  