<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251214093216 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, size INT DEFAULT NULL, is_available BOOLEAN DEFAULT true NOT NULL, published_on DATE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE IF EXISTS  newtable');
        //$this->addSql('ALTER TABLE task ADD deleted BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE task ALTER completed SET DEFAULT false');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE newtable (column1 VARCHAR DEFAULT NULL)');
        $this->addSql('DROP TABLE IF EXISTS product');
        //$this->addSql('ALTER TABLE task DROP deleted');
        $this->addSql('ALTER TABLE task ALTER completed DROP DEFAULT');
    }
}
